### ISSUE TITLE
I can't find any artifacts to download

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [pal1000/swiftshader-dist-win#9]

**Comment by pal1000** [comment]
Scroll down until you find a pipeline run that took about 1hr or more to complete. Only those have artifacts. The rest of pipelines detected no code change so they stopped quickly without building swiftshader or producing artifacts.

This is the latest pipeline run with artifacts at the time of writing this:  https://dev.azure.com/bontarka/swiftshader-dist-win/_build/results?buildId=3897&view=results

Also you would have known about this detail if you have red the readme more carefully:
> Binaries packages are created automatically on Azure Pipelines every 8 hours if there are changes either here or with swiftshader itself. **Builds will end quickly, under 10 minutes and with no binaries posted if there is no change**.

**Comment by BlohoJo** [comment]
The Azure Pipelines don't seem to serve users and developers who want compiled binaries, as currently, all usable binaries have been deleted. The only job currently available with artifacts has failed to build properly. So, there is nothing currently available. This isn't user friendly, and is a hindrance instead of a help.

**Comment by pal1000** [comment]
Try [this run](https://dev.azure.com/bontarka/swiftshader-dist-win/_build/results?buildId=3960&view=artifacts&pathAsName=false&type=publishedArtifacts) for now.

**Comment by BlohoJo** [comment]
Don't know how to do that.

I usually look for build time to tell if there's artifacts or not. Even though the oldest April 5 release has artifacts, the 17 minute build time doesn't show in the runs list. It's the only release that has artifacts, and is missing LLVM. That's what I need.

Don't understand the point of deleting releases. It leaves users with nothing.

**Comment by pal1000** [comment]
> Don't understand the point of deleting releases. It leaves users with nothing.

It is Azure runs retention policy. It purges them after a month.
> It's the only release that has artifacts, and is missing LLVM. That's what I need.

Any reason why subzero build isn't an option?

**Comment by BlohoJo** [comment]
LLVM10 continues to fail to build. Is this going to stay like this or will it be fixed at some point? Could you please make available the last LLVM10 binary that built successfully?

**Comment by tintanto** [comment]
This is still an issue. This is the second day where I look for artifacts and 0 artifacts to be seen. I would recommend creating some releases on github instead. @pal1000

**Comment by pal1000** [comment]
I looked at [last pipeline](https://dev.azure.com/bontarka/swiftshader-dist-win/_build/results?buildId=4076&view=results) [log](https://dev.azure.com/bontarka/0f71ca99-a6cd-4648-9ce3-12c03b9eced3/_apis/build/builds/4076/logs/21) with artifacts and it appears LLVM10 backend build fails due to compiler running out of heap space.

If any of you want to help you can work on converting build from Azure pipelines to GitHub actions. This is expected to touch/replace these files
- azure-pipelines.yml
- buildscript/ci/pushvar.cmd

Hopefully there should be no need to touch buildscript/ci/ci.cmd

**Comment by Dingo64** [comment]
There are no artifacts. Can't you just upload a ZIP with binaries here? We really don't need binaries compiled every few hours. We just need some that work, even if they are a few months old.

**Comment by pal1000** [comment]
Official binaries are present in Chrome or any Chromium based browser install folder. 

![Image](https://github.com/user-attachments/assets/52a8d87b-0747-48a2-a80c-e8785889502f)

**Comment by Dingo64** [comment]
Thank you so much!

**Comment by Alec269** [comment]
As of 29th May 2026. The only place where I could find the artifacts is:
https://dev.azure.com/bontarka/swiftshader-dist-win/_build/results?buildId=5407&view=results

**Comment by BlohoJo** [comment]
The Azure site is a confusing mess to navigate.

It does look like it's producing artifacts, they're just hard to find.

Try this link for the latest (05/29/2026):

https://dev.azure.com/bontarka/swiftshader-dist-win/_build/results?buildId=5491&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by TheAncientOwl** [comment]
I looked a lot after some binaries and finally found them [here](https://github.com/pal1000/swiftshader-dist-win/issues/9#issuecomment-4577960343) added by @BlohoJo. Thanks a lot!
For all following travellers, if that resource is no longer available, I uploaded it to one of my issues here ~ [here you go](https://github.com/TheAncientOwl/fluxion/issues/5#issuecomment-5654443395)
